// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  about: dynamic(() => import("./About")),
  accordion_info: dynamic(() => import("./PraticeAreas")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  offices: dynamic(() => import("./Offices")),
  publications: dynamic(() => import("./Publications")),
}
