// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic"

export const components = {
  accordion_info: dynamic(() => import("./AccordionInfo")),
  hero: dynamic(() => import("./Hero")),
}
